### ISSUE TITLE
fix: 매니저 대회 및 게임 생성 오류 수정

### ISSUE THREAD

**Issue by ohprettyhak** [hufscheer/web#343]
## TODO

- [ ] 게임 시작 시 `state = "PLAYING "` 값이 넘어가는 문제 해결
- [ ] 타인라인 - 연장전 변경 시 경기가 종료되는 문제 해결
- [ ] 대회 생성 시 종료일 시간을 "23:59"로 변경
