### ISSUE TITLE
fix: 타임라인 및 선수 선택 개선

### ISSUE THREAD

**Issue by ohprettyhak** [hufscheer/web#353]
## TODO

- [x] 타임라인 삭제 시 올바르지 않은 ID가 선택되는 문제 해결
- [x] 선수 변경 및 득점 추가 시 선수 번호를 같이 보여주도록 구현 
- [x] 게임 종료 텍스트 개선
